TYPE=VIEW
query=select `db_leave`.`leaves`.`leave_ID` AS `leave_ID`,`u1`.`name_en` AS `name_en`,`u1`.`surname_en` AS `surname_en`,`u1`.`name_th` AS `name_th`,`u1`.`surname_th` AS `surname_th`,`u2`.`name_en` AS `active_name_en`,`u2`.`surname_en` AS `active_surname_en`,`u2`.`name_th` AS `active_name_th`,`u2`.`surname_th` AS `active_surname_th`,`db_leave`.`leaves`.`subject` AS `subject`,`db_leave`.`leaves`.`detail` AS `detail`,`db_leave`.`leave_type`.`leave_type_Name` AS `leave_type_name`,`db_leave`.`leave_group`.`leave_group_Name` AS `leave_group_name`,`db_leave`.`leaves`.`start_date` AS `start_date`,`db_leave`.`leaves`.`end_date` AS `end_date`,`db_leave`.`leaves`.`total_date` AS `total_date`,`db_leave`.`leaves`.`active_date` AS `active_date`,`db_leave`.`acceptation`.`acceptation_Name` AS `acceptation_name`,`db_leave`.`leaves`.`leave_attached` AS `leave_attached`,`db_leave`.`acceptation`.`acceptation_ID` AS `acceptation_ID`,`db_leave`.`leaves`.`leave_type_ID` AS `leave_type_ID`,`u1`.`user_type_ID` AS `user_type_ID`,`u1`.`department_ID` AS `department_ID` from (((((`db_leave`.`leaves` join `db_leave`.`leave_type` on((`db_leave`.`leaves`.`leave_type_ID` = `db_leave`.`leave_type`.`leave_type_ID`))) join `db_leave`.`leave_group` on((`db_leave`.`leave_type`.`leave_group_ID` = `db_leave`.`leave_group`.`leave_group_ID`))) join `db_leave`.`acceptation` on((`db_leave`.`leaves`.`acceptation_ID` = `db_leave`.`acceptation`.`acceptation_ID`))) join `db_leave`.`user` `u1` on((`db_leave`.`leaves`.`user_leave` = `u1`.`user_ID`))) join `db_leave`.`user` `u2` on((`db_leave`.`leaves`.`active_by` = `u2`.`user_ID`))) where (`db_leave`.`leaves`.`delete_flag` = 0) order by `db_leave`.`leaves`.`active_date` desc
md5=ab0396c6af992fd291ec3e4c57c2d7c0
updatable=1
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
revision=1
timestamp=2016-02-01 13:04:19
create-version=1
source=select `leaves`.`leave_ID` AS `leave_ID`,`u1`.`name_en` AS `name_en`,`u1`.`surname_en` AS `surname_en`,`u1`.`name_th` AS `name_th`,`u1`.`surname_th` AS `surname_th`,`u2`.`name_en` AS `active_name_en`,`u2`.`surname_en` AS `active_surname_en`,`u2`.`name_th` AS `active_name_th`,`u2`.`surname_th` AS `active_surname_th`,`leaves`.`subject` AS `subject`,`leaves`.`detail` AS `detail`,`leave_type`.`leave_type_Name` AS `leave_type_name`,`leave_group`.`leave_group_Name` AS `leave_group_name`,`leaves`.`start_date` AS `start_date`,`leaves`.`end_date` AS `end_date`,`leaves`.`total_date` AS `total_date`,`leaves`.`active_date` AS `active_date`,`acceptation`.`acceptation_Name` AS `acceptation_name`,`leaves`.`leave_attached` AS `leave_attached`,`acceptation`.`acceptation_ID` AS `acceptation_ID`,`leaves`.`leave_type_ID` AS `leave_type_ID`,`u1`.`user_type_ID` AS `user_type_ID`,`u1`.`department_ID` AS `department_ID` from (((((`leaves` join `leave_type` on((`leaves`.`leave_type_ID` = `leave_type`.`leave_type_ID`))) join `leave_group` on((`leave_type`.`leave_group_ID` = `leave_group`.`leave_group_ID`))) join `acceptation` on((`leaves`.`acceptation_ID` = `acceptation`.`acceptation_ID`))) join `user` `u1` on((`leaves`.`user_leave` = `u1`.`user_ID`))) join `user` `u2` on((`leaves`.`active_by` = `u2`.`user_ID`))) where (`leaves`.`delete_flag` = 0) order by `leaves`.`active_date` desc
